version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/php/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "./"
    schedule:
      interval: "weekly"