services:
  phpunit:
    build:
      context: .
      dockerfile: docker/phpunit/Dockerfile
    container_name: AdventOfCode
    volumes:
      - .:/app
    tty: true  # Keeps the container running for interactive use